---

- name: Test distribution
  assert:
    that: >
      ansible_os_family == "RedHat"

- name: Add EPEL YUM repo
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: "{{ zabbix_server_epel_yumrepo_url }}"
    gpgcheck: no
    params: "{{ zabbix_server_epel_yumrepo_params }}"
  when: zabbix_server_epel_install
  tags:
    - zabbix_server_pkg

- name: Add Zabbix YUM repo
  yum_repository:
    name: zabbix
    description: Official Zabbix {{ zabbix_major_version }} YUM repo
    baseurl: "{{ zabbix_yumrepo_url }}"
    gpgcheck: no
    params: "{{ zabbix_yumrepo_params }}"
  tags:
    - zabbix_server_pkg

- name: Install Zabbix server
  yum:
    name: "{{ zabbix_server_pkg }}"
    state: present
  notify:
    - Restart Zabbix server
  tags:
    - zabbix_server_pkg

- name: Configure Zabbix server
  template:
    src: zabbix_server.conf.j2
    dest: "{{ zabbix_server_config_file }}"
  notify:
    - Restart Zabbix server
  tags:
    - zabbix_server_config

- name: Install dependency for PostreSQL user/db creation/import
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ zabbix_server_db_pgsql_pkgs }}"
  when: zabbix_server_db_engine == 'pgsql'
  tags:
    - zabbix_server_db

- name: Create PostgreSQL DB
  postgresql_db:
    name: "{{ zabbix_server_db_name }}"
    login_user: "{{ zabbix_server_db_login_user }}"
    login_password: "{{ zabbix_server_db_login_password }}"
    login_host: "{{ zabbix_server_db_host }}"
    port: "{{ zabbix_server_db_port }}"
  register: zabbix_server_db_pgsql_created
  when: zabbix_server_db_engine == 'pgsql'
  tags:
    - zabbix_server_db

- name: Create PostgreSQL user
  postgresql_user:
    name: "{{ zabbix_server_db_user }}"
    db: "{{ zabbix_server_db_name }}"
    password: "{{ zabbix_server_db_password }}"
    priv: ALL
    login_user: "{{ zabbix_server_db_login_user }}"
    login_password: "{{ zabbix_server_db_login_password }}"
    login_host: "{{ zabbix_server_db_host }}"
    port: "{{ zabbix_server_db_port }}"
  when: zabbix_server_db_engine == 'pgsql'
  tags:
    - zabbix_server_db

- name: Install dependency for MySQL user/db creation/import
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ zabbix_server_db_mysql_pkgs }}"
  when: zabbix_server_db_engine == 'mysql'
  tags:
    - zabbix_server_db

- name: Create MySQL DB
  mysql_db:
    name: "{{ zabbix_server_db_name }}"
    login_host: "{{ zabbix_server_db_host }}"
    login_port: "{{ zabbix_server_db_port }}"
    login_user: "{{ zabbix_server_db_login_user }}"
    login_password: "{{ zabbix_server_db_login_password }}"
    encoding: utf8
  register: zabbix_server_db_mysql_created
  when: zabbix_server_db_engine == 'mysql'
  tags:
    - zabbix_server_db

- name: Create MySQL user
  mysql_user:
    login_host: "{{ zabbix_server_db_host }}"
    login_port: "{{ zabbix_server_db_port }}"
    login_user: "{{ zabbix_server_db_login_user }}"
    login_password: "{{ zabbix_server_db_login_password }}"
    host: "{{ zabbix_server_db_user_host }}"
    name: "{{ zabbix_server_db_user }}"
    password: "{{ zabbix_server_db_password }}"
    priv: "{{ zabbix_server_db_name }}.*:ALL"
  when: zabbix_server_db_engine == 'mysql'
  tags:
    - zabbix_server_db

- name: Import Zabbix DB schema for PostgreSQL
  shell: >
    psql
    --username {{ zabbix_server_db_user }}
    --host {{ zabbix_server_db_host }}
    --port {{ zabbix_server_db_port }}
    --dbname {{ zabbix_server_db_name }}
    --file {{ item }}
  args:
    executable: /bin/bash
  environment:
    PGPASSWORD: "{{ zabbix_server_db_password }}"
  with_items:
    - "{{ zabbix_server_db_schema_dir }}/schema.sql"
    - "{{ zabbix_server_db_schema_dir }}/images.sql"
    - "{{ zabbix_server_db_schema_dir }}/data.sql"
  when: >
    zabbix_server_db_engine == 'pgsql' and
    zabbix_server_db_pgsql_created.changed
  tags:
    - zabbix_server_db

- name: Import Zabbix DB schema for MySQL
  shell: >
    mysql
    --user={{ zabbix_server_db_user }}
    --password={{ zabbix_server_db_password }}
    --host={{ zabbix_server_db_host }}
    --port={{ zabbix_server_db_port }}
    {{ zabbix_server_db_name }} < {{ item }}
  args:
    executable: /bin/bash
  with_items:
    - "{{ zabbix_server_db_schema_dir }}/schema.sql"
    - "{{ zabbix_server_db_schema_dir }}/images.sql"
    - "{{ zabbix_server_db_schema_dir }}/data.sql"
  when: >
    zabbix_server_db_engine == 'mysql' and
    zabbix_server_db_mysql_created.changed
  tags:
    - zabbix_server_db

- name: Make sure the Zabbix Server service is enabled
  service:
    name: zabbix-server
    enabled: yes
  tags:
    - zabbix_server_config

- name: Make sure the Zabbix server service is running
  service:
    name: zabbix-server
    state: started
  register: zabbix_server_service_started
  tags:
    - zabbix_server_config
    - zabbix_server_pkg
